### ISSUE TITLE
Entity speed depends on resolution

### ISSUE THREAD

**Issue by tkaden4** [Ukn0wnSoldure/ASG#4]
When changing resolution from 900 x 900 to 500 x 500, there was a considerable difference in speed of the player.

**Comment by tkaden4** [comment]
I fixed this in the most recent pull request

**Comment by aedans** [comment]
This isn't actually a bug. Once I implement scaling (so that the same number of tiles appear on 2000x2000 as 500x500; currently the 2000x2000 will show 16x the tiles) the player will need to move slower to compensate.

**Comment by tkaden4** [comment]
I managed to make the entire screen scale down to the resolution, do you want me to add that
